### PR TITLE
Add formatting and style-checks.

### PR DESCRIPTION
**Pull request by ksaaskil**
Now that there are multiple contributors to `meeshkan`, I think we could add formatting and style checks. This PR adds `black` and `flake8` following the example of https://github.com/meeshkan/py-http-types/pull/21 . Style checks are not yet fixed as there are so many of them and they probably require manual work. Therefore the linting step is also skipped in `python setup.py test`. 

- ~**You should only review `setup.py` and `README.md`, everything else is auto-formatted with black**~
- Suggestion for contributors: Switch on auto-formatting with black in your code editor
- [ ]  Add precommit hooks like Fredrik suggested?
- [ ]  Fix style errors and formatting errors

### CODE REVIEW

**Comment by fornwall** [comment]
@ksaaskil Do you want to fix the conflicts? Otherwise I can pick it up.

**Comment by ksaaskil** [comment]
> @ksaaskil Do you want to fix the conflicts? Otherwise I can pick it up.

Go ahead if you feel like it, I've done it a few times already since opening this PR :)

**Comment by fornwall** [comment]
@ksaaskil Yea, we should merge it as soon as it's fixed, to avoid merge conflicts from happening again :). We're ok to merge this as is (with conflicts resolved), right? Then do precommit hooks and style in separate PR:s?

**Comment by ksaaskil** [comment]
I'm fine with merging this as is once those are fixed and we can have separate PRs for the next steps!

**Comment by fornwall** [comment]
Should probably await https://github.com/meeshkan/meeshkan/pull/85 to avoid causing problems in merging that.

**Comment by ksaaskil** [comment]
Rebased the branch to include commits that add formatting and linting commands. None of the formatting is yet enforced or done, I should have left that for another PR so that's what I'll do here.

**Pull request merged**
