### PR TITLE
[DRAFT] Fantasy land from feedback

### PR DESCRIPTION
**Pull request by mikesol**

### CODE REVIEW

**Comment by mikesol** [comment]
Sketch based on:
- call with Carolyn and Fredrik
- feedback from devs

The general idea is to experiment with changing the value prop by focusing on *integration testing* and then working backwards from the test to the recording. Currently, we present information in the opposite direction.

I think this'd be a fun experiment, and it is not that far from what we have now - we'd just need a client library, which would be ~1000 lines of code to turn on the server and use its admin api.

**Comment by fornwall** [comment]
> If your app or service integrates with another app or service, integration testing is a good way to make sure that your code correctly handles input from the external source, including unexpected input.

We should also mention the other part: that it's a good way to make sure your code provides the external service with correct input data (and do https://github.com/meeshkan/meeshkan/issues/138).

**Comment by fornwall** [comment]
What do you think about highlighting "programmatic customisation" / callbacks more? I think that realistically one needs to have those for many good test cases (at least for the foreseeable future).

**Comment by mikesol** [comment]
Agreed

**Comment by fornwall** [comment]
Closing this as the PR is not needed to direct discussions at this point, and the content of it may emerge in smaller pieces going forward.

**Pull request closed without merging**
