### PR TITLE
Adds scope for server

### PR DESCRIPTION
**Pull request by mikesol**
Scope is a way to signal the current scope of the test.
For example, if we are testing A and then B, we set
the scope to A and then B, and by querying the scope, we can
assign API requests and responses to their logical "place"
in things like reports.

### CODE REVIEW

**Comment by ksaaskil** [comment]
`callback_manager` needs to be a global as it reads stuff via decorators (or at least some kind of "loaded callbacks" needs to be global), but I'm not sure we need a global `ScopeManager`?

**Comment by mikesol** [comment]
Cool with migrating out of globals, but what if internally we need information from the scope manager (ie the current scope) to do something (ie write a report file once something goes out of scope). If the scope manager is a dependency of the server, do we then have to call the admin server from the mock server? That’s fine ofc, but just trying to imagine the flow.

**Comment by ksaaskil** [comment]
> Cool with migrating out of globals, but what if internally we need information from the scope manager (ie the current scope) to do something (ie write a report file once something goes out of scope). If the scope manager is a dependency of the server, do we then have to call the admin server from the mock server? That’s fine ofc, but just trying to imagine the flow.

Both admin and mock server should then, in my opinion, at least explicitly state that their `ScopeManager` instance is the global `scope_manager`. The views don't need to know if they refer to a global or not, they just refer to `self.scope_manager`. Maybe we need the globals, but I would just be careful of not ending up in spaghetti code 🤔

**Comment by mikesol** [comment]
My recommendation @ksaaskil would be to call the admin API from the mock API and to have no globals at all.

**Pull request merged**
