### PR TITLE
Add CLI with Click

### PR DESCRIPTION
**Pull request by ksaaskil**
- Add CLI with [Click](https://click.palletsprojects.com/en/7.x/), it's easy to add new commands and it automatically adds help messages, input validation, and such
- Reorganize tests a bit

TODO:
- [x]  CLI and the tests are really slow because schema is built in a really dumb way, I'll work on that next

### CODE REVIEW

**Comment by ksaaskil** [comment]
Added a few more commits to update schema step-by-step when reading from file.

**Comment by aby2s** [comment]
We could also keep the ability to transform pcap/tshark files into jsonl or directly into OpenAPI. It'll be a nice feature if it is available from the meeshkan main script.

**Comment by ksaaskil** [comment]
> We could also keep the ability to transform pcap/tshark files into jsonl or directly into OpenAPI. It'll be a nice feature if it is available from the meeshkan main script.

Yeah I can add those later on.

**Comment by ksaaskil** [comment]
Added https://github.com/Meeshkan/meeshkan/issues/8 for adding the pcap support.

**Pull request merged**
